### ISSUE TITLE
File not read when doing ingest 

### ISSUE THREAD

**Issue by godfriedmeesters** [CybercentreCanada/assemblyline_client#1]
After doing  `al_client.ingest(file_path)` , the file is  submitted, however when checking the file in the dashboard in "submission details", the file is shown as a file with "unknown" format, and the contents of the file is simply `file_path`. 

Replacing   `al_client.ingest` with `al_client.submit` resolved this issue.

**Comment by godfriedmeesters** [comment]
With `submit` it works, but when i want to get the result using` al_client.ingest.get_message_list`, I get nothing.

**Comment by cccs-sgaron** [comment]
This turned out not to be a bug. Both submit and ingest use KWARGS for their parameters but the first parameter for submit was the file path and the first parameter for ingest was the file content.

It is recommended that you specify what the parameter is so instead of using al_client.submit(file_path) you should use al_client.submit(path=file_path).

Regardless of this, I still did a code change to make the parameter order match between ingest and submit for consistency purposes. You should still use path=file_path just to be safe.

**Comment by cccs-sgaron** [comment]
If you want the latest assemblyline_client that matches submit and ingest parameters order, just install it by doing this: **pip install -U assemblyline_client --pre**

**Comment by godfriedmeesters** [comment]
Ok thanks!
